server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:${PWD}/configuration-repository
  security:
    user:
      name: username
      password: password

logging:
  level:
    root: info

encrypt:
  key: my_encryption_key

management:
  endpoint.health.show-details: always
  endpoints.web.exposure.include: "*"

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config:
      server:
        native:
          search-locations: file:/configuration-repository