apiVersion: v2
appVersion: "4.0.0"
description: Helm Chart for Spring Cloud Configuration Server
name: config-server
version: 1.0.0

dependencies:
  - name: common
    version: 1.0.0
    repository: file://../../common