server:
  port: 7003
  error:
    include-message: always

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/reviewdb?protocol=tcp
    username: mysql-user-dev
    password: mysql-pass-dev
    hikari:
      initialization-fail-timeout: 60000

logging:
  level:
    root: info
    org.emangini.servolution: debug
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql/reviewdb?protocol=tcp

server:
  port: 8080
